#!/usr/bin/env python3
"""Fix all translated page titles and meta descriptions."""
import re
from pathlib import Path

BASE = Path("/tmp/exknowledge")

def update_file(filepath, new_title, new_desc):
    content = filepath.read_text(encoding='utf-8')
    content = re.sub(r'<title>[^<]*</title>', f'<title>{new_title}</title>', content, count=1)
    content = re.sub(r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{new_desc}">', content, count=1)
    content = re.sub(r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{new_desc}">', content, count=1)
    filepath.write_text(content, encoding='utf-8')

DATA = {
"de": {
    "index": ("ATEX & Ex-Schutz Wissensdatenbank – ExKnowledge", "Praxiswissen zu ATEX, IECEx und Explosionsschutz. Zoneneinteilung, Schutzarten, Gerätekategorien und Normen – verständlich erklärt für Ingenieure und Techniker."),
    "atex-directive": ("ATEX-Richtlinie 2014/34/EU – Alles Wichtige", "Die ATEX-Richtlinie verständlich erklärt: Geltungsbereich, Konformitätsbewertung, CE-Kennzeichnung und Pflichten für Hersteller von Ex-Geräten."),
    "atex-for-beginners": ("ATEX für Einsteiger – Einfach erklärt", "ATEX-Grundlagen verständlich aufbereitet: Zonen, Gerätekategorien, Ex-Kennzeichnung und Schutzkonzepte. Der ideale Einstieg in den Explosionsschutz."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Unterschiede im Vergleich", "ATEX und IECEx im direkten Vergleich: Geltungsbereich, Rechtsgrundlage, Kennzeichnung und Zertifizierungsverfahren. Welcher Standard wann gilt."),
    "cable-glands-hazardous-areas": ("Ex-Kabelverschraubungen – Typen und Auswahl", "Kabelverschraubungen für Ex-Bereiche: Druckfeste (Ex d), erhöhte Sicherheit (Ex e) und Barriere-Typen. Gewindestandards, IP-Schutz und Montagetipps."),
    "compex-certification": ("CompEx-Zertifizierung – Module und Karriere", "Alles zur CompEx-Zertifizierung: Module Ex01–Ex14, Schulungsinhalte, Gültigkeitsdauer und berufliche Vorteile für Ex-Fachkräfte."),
    "dust-explosion-protection": ("Staubexplosionsschutz – Zonen und Maßnahmen", "Schutz vor Staubexplosionen: Brennbare Stäube, Zoneneinteilung 20/21/22, Zündquellen erkennen und geeignete Schutzmaßnahmen nach IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Ex-Geräte richtig auswählen – Praxisleitfaden", "Schritt für Schritt zum richtigen Ex-Gerät: Entscheidungsdiagramme, Zuordnung Zone-Kategorie und Vergleich der Schutzarten für jeden Einsatzbereich."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Druckfest oder eigensicher?", "Druckfeste Kapselung (Ex d) und Eigensicherheit (Ex i) im technischen Vergleich: Funktionsprinzipien, Einsatzbereiche und Entscheidungshilfen."),
    "hazardous-area-classification": ("Zoneneinteilung explosionsgefährdeter Bereiche", "So werden Ex-Bereiche klassifiziert: Methodik, Freisetzungsquellen, Belüftungsbewertung und Dokumentation nach IEC 60079-10. Praxisnah erklärt."),
    "how-to-read-atex-nameplate": ("ATEX-Typenschild lesen und verstehen", "ATEX-Typenschilder richtig entschlüsseln: CE-Zeichen, Gerätekategorien, Ex-Kennzeichnung, Temperaturklassen und Sonderbedingungen anhand realer Beispiele."),
    "hydrogen-explosion-protection": ("Explosionsschutz bei Wasserstoff – IIC-Geräte", "Wasserstoff erfordert besonderen Explosionsschutz: Breiter Zündbereich, niedrige Zündenergie. So wählen Sie IIC-zertifizierte Geräte richtig aus."),
    "certification": ("Ex-Zertifizierung – ATEX und IECEx Verfahren", "Überblick über Ex-Zertifizierungsverfahren nach ATEX und IECEx: Prüfstellen, Baumusterprüfung, Qualitätssicherung und Konformitätsbewertung."),
    "cheat-sheet": ("ATEX-Spickzettel – Schnellreferenz", "ATEX und Ex-Schutz auf einen Blick: Zonen, Kategorien, Temperaturklassen und Schutzarten als praktische Schnellreferenz zum Nachschlagen."),
    "epl": ("Equipment Protection Level (EPL) – Übersicht", "Equipment Protection Levels (EPL) nach IEC 60079-0 erklärt: Ga/Gb/Gc, Da/Db/Dc und Ma/Mb. Zuordnung zu ATEX-Kategorien und Zonen."),
    "ex-markings": ("Ex-Kennzeichnung verstehen – Markierungen", "Ex-Kennzeichnungen entschlüsseln: Schutzarten, Gasgruppen, Temperaturklassen und EPL. So lesen Sie die Markierung auf Ex-Geräten richtig."),
    "faq": ("Häufige Fragen zu ATEX und Explosionsschutz", "Antworten auf die häufigsten Fragen zu ATEX, IECEx, Zoneneinteilung, Schutzarten und Ex-Kennzeichnung. Schnelle Orientierung für Einsteiger."),
    "fundamentals": ("Grundlagen des Explosionsschutzes", "Die Basis des Explosionsschutzes: Explosionsdreieck, Zündquellen, Schutzprinzipien und Zusammenhang zwischen Zonen, Kategorien und Schutzarten."),
    "gas-groups": ("Gasgruppen IIA, IIB, IIC – Übersicht", "Gasgruppen im Explosionsschutz erklärt: IIA, IIB und IIC nach IEC 60079-20-1. Einteilung, Grenzspaltweiten, Zündströme und typische Gase."),
    "installation-inspection": ("Ex-Installation und Inspektion – Leitfaden", "Anforderungen an Installation und Inspektion von Ex-Anlagen: IEC 60079-14/17, Erstprüfung, wiederkehrende Prüfungen und Dokumentation."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Systemvergleich", "Nordamerikanisches NEC 500/505 und europäisches ATEX/IEC-System im Vergleich: Divisions vs. Zonen, Schutzverfahren und gegenseitige Anerkennung."),
    "protection-methods": ("Ex-Schutzarten – Alle Zündschutzarten", "Alle Ex-Schutzarten im Überblick: Druckfeste Kapselung (d), Eigensicherheit (i), Vergusskapselung (m), Überdruckkapselung (p) und weitere."),
    "standards": ("Explosionsschutz-Normen – IEC 60079 Serie", "Übersicht der wichtigsten Normen im Explosionsschutz: IEC 60079-Reihe, EN-Normen und deren Anwendungsbereiche für Ex-Geräte und -Anlagen."),
    "temperature-classes": ("Temperaturklassen T1–T6 im Ex-Schutz", "Temperaturklassen T1 bis T6 erklärt: Maximale Oberflächentemperaturen, Zuordnung zu Gasen und Bedeutung für die Geräteauswahl im Ex-Bereich."),
    "zone-classification": ("Zonenklassifizierung – Zone 0, 1, 2, 20–22", "Zonenklassifizierung für Gas und Staub: Zone 0/1/2 und Zone 20/21/22 nach IEC 60079-10. Definitionen, Beispiele und Vorgehensweise."),
    "atex-equipment-categories": ("ATEX-Gerätekategorien 1, 2 und 3", "ATEX-Gerätekategorien M1/M2, 1/2/3 erklärt: Schutzniveaus, erlaubte Zonen und Anforderungen an die Konformitätsbewertung nach 2014/34/EU."),
    "dsear-regulations-uk": ("DSEAR-Verordnung (UK) – Übersicht", "Die britische DSEAR-Verordnung zum Explosionsschutz: Pflichten des Arbeitgebers, Risikobeurteilung und Unterschiede zur europäischen ATEX 153."),
},
"es": {
    "index": ("Base de conocimiento ATEX y Ex – ExKnowledge", "Conocimiento práctico sobre ATEX, IECEx y protección contra explosiones. Zonas, métodos de protección, categorías de equipos y normativas explicadas."),
    "atex-directive": ("Directiva ATEX 2014/34/UE – Guía completa", "La directiva ATEX de equipos explicada: alcance, evaluación de conformidad, marcado CE y obligaciones del fabricante de equipos Ex."),
    "atex-for-beginners": ("ATEX para principiantes – Guía básica", "Conceptos básicos de ATEX en español: zonas, categorías de equipos, marcado Ex y principios de protección. Tu primer paso en seguridad antiexplosión."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Diferencias clave", "ATEX e IECEx comparados: alcance geográfico, base legal, marcado y certificación. Descubre cuándo aplica cada norma de protección antiexplosión."),
    "cable-glands-hazardous-areas": ("Prensaestopas Ex – Tipos y selección", "Prensaestopas para zonas con riesgo de explosión: antideflagrantes (Ex d), seguridad aumentada (Ex e) y barrera. Roscas, IP y errores frecuentes."),
    "compex-certification": ("Certificación CompEx – Módulos y carrera", "Todo sobre CompEx: módulos Ex01–Ex14, requisitos de formación, validez, renovación y ventajas profesionales para trabajar en zonas peligrosas."),
    "dust-explosion-protection": ("Protección contra explosiones de polvo", "Prevención de explosiones de polvo: tipos de polvo combustible, zonas 20/21/22, fuentes de ignición y selección de equipos según IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Selección de equipos Ex – Guía práctica", "Cómo elegir equipos Ex paso a paso: diagramas de decisión, relación zona-categoría, comparación de métodos de protección y recomendaciones."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Antideflagrante o seguridad?", "Envolvente antideflagrante (Ex d) frente a seguridad intrínseca (Ex i): principios, aplicaciones y criterios de selección para ingenieros."),
    "hazardous-area-classification": ("Clasificación de áreas peligrosas – Guía", "Cómo se clasifican las áreas peligrosas en zonas: metodología, fuentes de emisión, ventilación y documentación según IEC 60079-10."),
    "how-to-read-atex-nameplate": ("Leer una placa ATEX – Guía de decodificación", "Aprende a interpretar placas ATEX paso a paso: marcado CE, categorías, marcado Ex, clases de temperatura y condiciones especiales con ejemplos."),
    "hydrogen-explosion-protection": ("Protección antiexplosión para hidrógeno", "El hidrógeno exige protección especial: amplio rango de inflamabilidad y baja energía de ignición. Guía para seleccionar equipos IIC correctamente."),
    "certification": ("Certificación Ex – Procesos ATEX e IECEx", "Procesos de certificación Ex según ATEX e IECEx: organismos notificados, ensayo de tipo, aseguramiento de calidad y evaluación de conformidad."),
    "cheat-sheet": ("Hoja de referencia ATEX – Consulta rápida", "ATEX y protección Ex en una página: zonas, categorías, clases de temperatura y métodos de protección como referencia rápida."),
    "epl": ("Nivel de Protección del Equipo (EPL)", "Niveles de protección del equipo según IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc y Ma/Mb. Relación con categorías ATEX y zonas."),
    "ex-markings": ("Marcado Ex – Cómo interpretarlo", "Entiende el marcado Ex: métodos de protección, grupos de gas, clases de temperatura y EPL. Guía para interpretar marcas en equipos Ex."),
    "faq": ("Preguntas frecuentes sobre ATEX y Ex", "Respuestas a las preguntas más comunes sobre ATEX, IECEx, clasificación de zonas, métodos de protección y marcado Ex."),
    "fundamentals": ("Fundamentos de protección contra explosiones", "Bases de la protección antiexplosión: triángulo de explosión, fuentes de ignición, principios de protección y relación zonas-categorías."),
    "gas-groups": ("Grupos de gas IIA, IIB, IIC – Guía", "Grupos de gas en protección antiexplosión: IIA, IIB e IIC según IEC 60079-20-1. Clasificación, intersticios y gases típicos."),
    "installation-inspection": ("Instalación e inspección Ex – Requisitos", "Requisitos para instalación e inspección de equipos Ex: IEC 60079-14/17, verificación inicial, inspecciones periódicas y documentación."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Comparación", "Sistema norteamericano NEC 500/505 frente al europeo ATEX/IEC: Divisions vs. zonas, métodos de protección y reconocimiento mutuo."),
    "protection-methods": ("Métodos de protección Ex – Todos los tipos", "Todos los métodos de protección Ex: envolvente antideflagrante (d), seguridad intrínseca (i), encapsulado (m), presurización (p) y más."),
    "standards": ("Normas de protección antiexplosión – IEC", "Las normas clave de protección antiexplosión: serie IEC 60079, normas EN y sus ámbitos de aplicación para equipos e instalaciones Ex."),
    "temperature-classes": ("Clases de temperatura T1–T6 en Ex", "Clases de temperatura T1 a T6 explicadas: temperaturas superficiales máximas, gases asociados y su importancia en la selección de equipos."),
    "zone-classification": ("Clasificación de zonas – 0, 1, 2, 20–22", "Clasificación de zonas para gas y polvo: zona 0/1/2 y zona 20/21/22 según IEC 60079-10. Definiciones, ejemplos y metodología."),
    "atex-equipment-categories": ("Categorías de equipos ATEX – 1, 2 y 3", "Categorías ATEX M1/M2, 1/2/3: niveles de protección, zonas permitidas y requisitos de evaluación de conformidad según 2014/34/UE."),
    "dsear-regulations-uk": ("Reglamento DSEAR (Reino Unido) – Resumen", "Reglamento británico DSEAR sobre protección antiexplosión: obligaciones del empleador, evaluación de riesgos y diferencias con la ATEX 153 europea."),
},
"it": {
    "index": ("Base di conoscenza ATEX e Ex – ExKnowledge", "Conoscenza pratica su ATEX, IECEx e protezione antiesplosione. Zone, metodi di protezione, categorie di apparecchiature e normative spiegate."),
    "atex-directive": ("Direttiva ATEX 2014/34/UE – Guida completa", "La direttiva ATEX sulle apparecchiature spiegata: campo di applicazione, valutazione di conformità, marcatura CE e obblighi del fabbricante."),
    "atex-for-beginners": ("ATEX per principianti – Guida semplice", "Le basi di ATEX in italiano: zone, categorie di apparecchiature, marcatura Ex e concetti di protezione. Il punto di partenza ideale."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Differenze a confronto", "ATEX e IECEx a confronto: ambito geografico, base giuridica, marcatura e certificazione. Scopri quando si applica ciascuna norma."),
    "cable-glands-hazardous-areas": ("Pressacavi Ex – Tipologie e scelta", "Pressacavi per zone Ex: antideflagranti (Ex d), sicurezza aumentata (Ex e) e a barriera. Filettature, IP e errori comuni da evitare."),
    "compex-certification": ("Certificazione CompEx – Moduli e carriera", "Tutto su CompEx: moduli Ex01–Ex14, requisiti di formazione, validità, rinnovo e vantaggi professionali per il lavoro in aree pericolose."),
    "dust-explosion-protection": ("Protezione esplosioni polveri – Zone e misure", "Protezione contro esplosioni di polveri: polveri combustibili, zone 20/21/22, sorgenti di innesco e scelta apparecchiature per IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Scelta apparecchiature Ex – Guida pratica", "Come scegliere le apparecchiature Ex passo dopo passo: diagrammi decisionali, rapporto zona-categoria e confronto metodi di protezione."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Antideflagrante o sicurezza?", "Custodia antideflagrante (Ex d) e sicurezza intrinseca (Ex i) a confronto tecnico: principi, applicazioni e criteri di scelta."),
    "hazardous-area-classification": ("Classificazione aree pericolose – Guida", "Come vengono classificate le aree pericolose in zone: metodologia, sorgenti di emissione, ventilazione e documentazione per IEC 60079-10."),
    "how-to-read-atex-nameplate": ("Leggere la targhetta ATEX – Guida completa", "Impara a interpretare le targhette ATEX: marcatura CE, categorie, marcatura Ex, classi di temperatura e condizioni speciali con esempi."),
    "hydrogen-explosion-protection": ("Protezione antiesplosione idrogeno – IIC", "L'idrogeno richiede protezione speciale: ampio campo di infiammabilità e bassa energia di innesco. Guida alla scelta di apparecchiature IIC."),
    "certification": ("Certificazione Ex – Processi ATEX e IECEx", "Panoramica della certificazione Ex secondo ATEX e IECEx: enti notificati, esame di tipo, garanzia qualità e valutazione di conformità."),
    "cheat-sheet": ("Scheda rapida ATEX – Riferimento veloce", "ATEX e protezione Ex in una pagina: zone, categorie, classi di temperatura e metodi di protezione come pratico riferimento rapido."),
    "epl": ("Equipment Protection Level (EPL) – Guida", "Equipment Protection Levels secondo IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc e Ma/Mb. Relazione con categorie ATEX e zone."),
    "ex-markings": ("Marcatura Ex – Come interpretarla", "Comprendere la marcatura Ex: metodi di protezione, gruppi gas, classi di temperatura e EPL. Come leggere la marcatura Ex correttamente."),
    "faq": ("Domande frequenti su ATEX e protezione Ex", "Risposte alle domande più frequenti su ATEX, IECEx, classificazione zone, metodi di protezione e marcatura Ex."),
    "fundamentals": ("Fondamenti di protezione antiesplosione", "Le basi della protezione antiesplosione: triangolo dell'esplosione, sorgenti di innesco, principi di protezione e relazione zone-categorie."),
    "gas-groups": ("Gruppi gas IIA, IIB, IIC – Panoramica", "Gruppi gas nella protezione antiesplosione: IIA, IIB e IIC secondo IEC 60079-20-1. Classificazione, interstizi e gas tipici."),
    "installation-inspection": ("Installazione e ispezione Ex – Requisiti", "Requisiti per installazione e ispezione di impianti Ex: IEC 60079-14/17, verifica iniziale, ispezioni periodiche e documentazione."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Confronto", "Sistema nordamericano NEC 500/505 e europeo ATEX/IEC a confronto: Divisions vs. zone, metodi di protezione e riconoscimento reciproco."),
    "protection-methods": ("Metodi di protezione Ex – Tutti i tipi", "Tutti i metodi di protezione Ex: custodia antideflagrante (d), sicurezza intrinseca (i), incapsulamento (m), pressurizzazione (p) e altri."),
    "standards": ("Norme protezione antiesplosione – IEC 60079", "Panoramica delle principali norme di protezione antiesplosione: serie IEC 60079, norme EN e relativi ambiti di applicazione."),
    "temperature-classes": ("Classi di temperatura T1–T6 in Ex", "Classi di temperatura T1–T6 spiegate: temperature superficiali massime, gas associati e importanza nella scelta delle apparecchiature."),
    "zone-classification": ("Classificazione zone – 0, 1, 2, 20–22", "Classificazione zone per gas e polveri: zona 0/1/2 e zona 20/21/22 secondo IEC 60079-10. Definizioni, esempi e metodologia."),
    "atex-equipment-categories": ("Categorie apparecchiature ATEX – 1, 2, 3", "Categorie ATEX M1/M2, 1/2/3: livelli di protezione, zone ammesse e requisiti di valutazione conformità secondo 2014/34/UE."),
    "dsear-regulations-uk": ("Normativa DSEAR (UK) – Sintesi", "Normativa britannica DSEAR per la protezione antiesplosione: obblighi del datore di lavoro, valutazione rischi e differenze con ATEX 153."),
},
"fi": {
    "index": ("ATEX & Ex-suojaus tietopankki – ExKnowledge", "Käytännön tietoa ATEX:sta, IECEx:stä ja räjähdyssuojauksesta. Vyöhykeluokitus, suojausmenetelmät, laiteluokat ja standardit selkeästi selitettynä."),
    "atex-directive": ("ATEX-direktiivi 2014/34/EU – Opas", "ATEX-laitedirektiivi selkeästi selitettynä: soveltamisala, vaatimustenmukaisuuden arviointi, CE-merkintä ja valmistajan velvollisuudet."),
    "atex-for-beginners": ("ATEX aloittelijoille – Selkeä johdanto", "ATEX-perusteet ymmärrettävästi: vyöhykkeet, laiteluokat, Ex-merkinnät ja suojauskonseptit. Täydellinen lähtökohta räjähdyssuojaukseen."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Erot selitettynä", "ATEX ja IECEx vertailussa: maantieteellinen soveltamisala, oikeudellinen perusta, merkintäerot ja sertifiointiprosessit."),
    "cable-glands-hazardous-areas": ("Ex-kaapeliläpiviennit – Tyypit ja valinta", "Kaapeliläpiviennit Ex-alueille: paineenkestävät (Ex d), korotettu turvallisuus (Ex e) ja estetyypit. Kierrestandardit ja IP-luokat."),
    "compex-certification": ("CompEx-sertifiointi – Moduulit ja ura", "Kaikki CompEx:stä: moduulit Ex01–Ex14, koulutusvaatimukset, voimassaolo, uusinta ja urahyödyt räjähdysvaarallisten tilojen työhön."),
    "dust-explosion-protection": ("Pölyräjähdyssuojaus – Vyöhykkeet ja toimet", "Suojautuminen pölyräjähdyksiltä: palavat pölyt, vyöhykeluokitus 20/21/22, syttymislähteet ja laitevalinta IEC 60079-10-2 mukaan."),
    "ex-equipment-selection-guide": ("Ex-laitteiden valinta – Käytännön opas", "Oikea Ex-laite askel askeleelta: päätöskaaviot, vyöhyke-luokka-yhteys ja suojausmenetelmien vertailu eri käyttökohteisiin."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Paineenkestävä vai turvallinen?", "Paineenkestävä kotelointi (Ex d) ja luontainen turvallisuus (Ex i) teknisessä vertailussa: toimintaperiaatteet ja valintakriteerit."),
    "hazardous-area-classification": ("Räjähdysvaarallisten tilojen luokitus", "Näin Ex-tilat luokitellaan vyöhykkeisiin: menetelmä, päästölähteet, ilmanvaihtoarviointi ja dokumentointivaatimukset IEC 60079-10 mukaan."),
    "how-to-read-atex-nameplate": ("ATEX-tyyppikilven lukeminen – Opas", "Opi tulkitsemaan ATEX-tyyppikilpiä: CE-merkintä, laiteluokat, Ex-merkinnät, lämpötilaluokat ja erityisehdot todellisilla esimerkeillä."),
    "hydrogen-explosion-protection": ("Vetyräjähdyssuojaus – IIC-laitteet", "Vety vaatii erityistä räjähdyssuojausta: laaja syttymisalue ja matala syttymisenergia. Opas IIC-hyväksyttyjen laitteiden valintaan."),
    "certification": ("Ex-sertifiointi – ATEX ja IECEx prosessit", "Katsaus Ex-sertifiointiin ATEX:n ja IECEx:n mukaan: testauslaitokset, tyyppikoe, laadunvarmistus ja vaatimustenmukaisuuden arviointi."),
    "cheat-sheet": ("ATEX-muistilista – Pikaopas", "ATEX ja Ex-suojaus yhdellä sivulla: vyöhykkeet, luokat, lämpötilaluokat ja suojausmenetelmät kätevästi pikaoppaana."),
    "epl": ("Equipment Protection Level (EPL) – Opas", "Equipment Protection Levels IEC 60079-0 mukaan: Ga/Gb/Gc, Da/Db/Dc ja Ma/Mb. Yhteys ATEX-luokkiin ja vyöhykkeisiin."),
    "ex-markings": ("Ex-merkinnät – Tulkintaopas", "Ymmärrä Ex-merkinnät: suojausmenetelmät, kaasuryhmät, lämpötilaluokat ja EPL. Opas Ex-laitteiden merkintöjen lukemiseen."),
    "faq": ("Usein kysytyt kysymykset – ATEX ja Ex", "Vastaukset yleisimpiin kysymyksiin ATEX:sta, IECEx:stä, vyöhykeluokituksesta, suojausmenetelmistä ja Ex-merkinnöistä."),
    "fundamentals": ("Räjähdyssuojauksen perusteet", "Räjähdyssuojauksen perusteet: räjähdyskolmio, syttymislähteet, suojausperiaatteet ja vyöhykkeiden, luokkien ja menetelmien yhteys."),
    "gas-groups": ("Kaasuryhmät IIA, IIB, IIC – Katsaus", "Kaasuryhmät räjähdyssuojauksessa: IIA, IIB ja IIC IEC 60079-20-1 mukaan. Luokitus, rakoleveydet ja tyypilliset kaasut."),
    "installation-inspection": ("Ex-asennus ja tarkastus – Vaatimukset", "Vaatimukset Ex-laitteistojen asennukselle ja tarkastukselle: IEC 60079-14/17, alkutarkastus, määräaikaistarkastukset ja dokumentointi."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Vertailu", "Pohjoisamerikkalainen NEC 500/505 ja eurooppalainen ATEX/IEC vertailussa: Divisions vs. vyöhykkeet ja suojausmenetelmät."),
    "protection-methods": ("Ex-suojausmenetelmät – Kaikki tyypit", "Kaikki Ex-suojausmenetelmät: paineenkestävä kotelointi (d), luontainen turvallisuus (i), valumassa (m), ylipaineistus (p) ja muut."),
    "standards": ("Räjähdyssuojausstandardit – IEC 60079", "Katsaus räjähdyssuojauksen tärkeimpiin standardeihin: IEC 60079-sarja, EN-standardit ja niiden soveltamisalueet."),
    "temperature-classes": ("Lämpötilaluokat T1–T6 Ex-suojauksessa", "Lämpötilaluokat T1–T6 selitettynä: pintalämpötilat, kaasut ja merkitys laitevalinnassa räjähdysvaarallisissa tiloissa."),
    "zone-classification": ("Vyöhykeluokitus – Vyöhyke 0, 1, 2, 20–22", "Vyöhykeluokitus kaasuille ja pölyille: vyöhyke 0/1/2 ja vyöhyke 20/21/22 IEC 60079-10 mukaan. Määritelmät ja esimerkit."),
    "atex-equipment-categories": ("ATEX-laiteluokat 1, 2 ja 3", "ATEX-laiteluokat M1/M2, 1/2/3: suojaustasot, sallitut vyöhykkeet ja vaatimustenmukaisuuden arviointivaatimukset 2014/34/EU mukaan."),
    "dsear-regulations-uk": ("DSEAR-sääntely (UK) – Yleiskatsaus", "Iso-Britannian DSEAR-sääntely räjähdyssuojauksessa: työnantajan velvollisuudet, riskinarviointi ja erot eurooppalaiseen ATEX 153."),
},
"no": {
    "index": ("ATEX og Ex-vern kunnskapsbase – ExKnowledge", "Praktisk kunnskap om ATEX, IECEx og eksplosjonsvern. Soneklassifisering, vernemetoder, utstyrskategorier og standarder – forklart for ingeniører."),
    "atex-directive": ("ATEX-direktivet 2014/34/EU forklart", "Alt om ATEX-utstyrsdirektivet: virkeområde, samsvarsvurdering, CE-merking og krav til produsenter av Ex-utstyr."),
    "atex-for-beginners": ("ATEX for nybegynnere – Enkel innføring", "Grunnleggende om ATEX på norsk: soner, utstyrskategorier, Ex-merking og vernekonsepter. Perfekt startpunkt for deg som er ny i eksplosjonsvern."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Forskjeller forklart", "ATEX og IECEx sammenlignet: geografisk virkeområde, rettsgrunnlag, merkekrav og sertifiseringsprosesser. Finn ut hvilken standard som gjelder."),
    "cable-glands-hazardous-areas": ("Ex-kabelgjennomføringer – Typer og valg", "Kabelgjennomføringer for Ex-områder: flammesikre (Ex d), forhøyet sikkerhet (Ex e) og barrieretyper. Gjengstandarder, IP-klasser og vanlige feil."),
    "compex-certification": ("CompEx-sertifisering – Moduler og karriere", "Alt om CompEx: moduler Ex01–Ex14, opplæringskrav, gyldighet, fornyelse og karrierefordeler for arbeid i eksplosjonsutsatte områder."),
    "dust-explosion-protection": ("Støveksplosjonsvern – Soner og tiltak", "Vern mot støveksplosjoner: brennbart støv, soneklassifisering 20/21/22, tennkilder og riktig valg av tiltak etter IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Velge riktig Ex-utstyr – Praktisk guide", "Steg for steg til riktig Ex-utstyr: beslutningsdiagrammer, kobling mellom soner og kategorier, og sammenligning av vernemetoder."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Flammesikker eller egensikker?", "Flammesikker kapsel (Ex d) og egensikkerhet (Ex i) i teknisk sammenligning: virkemåte, bruksområder og valgkriterier for ingeniører."),
    "hazardous-area-classification": ("Klassifisering av eksplosjonsfarlige områder", "Slik klassifiseres Ex-områder i soner: metode, utslippskilder, ventilasjonsvurdering og dokumentasjonskrav etter IEC 60079-10."),
    "how-to-read-atex-nameplate": ("Lese ATEX-typeskilt – Komplett guide", "Slik avkoder du ATEX-typeskilter: CE-merking, utstyrskategorier, Ex-merking, temperaturklasser og spesialvilkår med reelle eksempler."),
    "hydrogen-explosion-protection": ("Eksplosjonsvern for hydrogen – IIC-utstyr", "Hydrogen krever spesielt eksplosjonsvern: bredt tennområde og lav tennenergi. Slik velger du riktig IIC-sertifisert utstyr."),
    "certification": ("Ex-sertifisering – ATEX og IECEx prosesser", "Oversikt over Ex-sertifisering etter ATEX og IECEx: prøveinstitusjoner, typegodkjenning, kvalitetssikring og samsvarsvurdering."),
    "cheat-sheet": ("ATEX-jukselapp – Hurtigreferanse", "ATEX og Ex-vern på én side: soner, kategorier, temperaturklasser og vernemetoder som praktisk hurtigreferanse."),
    "epl": ("Equipment Protection Level (EPL) forklart", "Equipment Protection Levels etter IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc og Ma/Mb. Kobling til ATEX-kategorier og soner."),
    "ex-markings": ("Ex-merking – Slik leser du merkingen", "Forstå Ex-merking: vernemetoder, gasgrupper, temperaturklasser og EPL. Slik tolker du merkingen på Ex-utstyr korrekt."),
    "faq": ("Vanlige spørsmål om ATEX og Ex-vern", "Svar på vanlige spørsmål om ATEX, IECEx, soneinndeling, vernemetoder og Ex-merking. Rask oversikt for nybegynnere og fagfolk."),
    "fundamentals": ("Grunnleggende om eksplosjonsvern", "Eksplosjonsvern fra grunnen: eksplosjonstrekanten, tennkilder, verneprinsipper og sammenhengen mellom soner, kategorier og vernemetoder."),
    "gas-groups": ("Gasgrupper IIA, IIB, IIC – Oversikt", "Gasgrupper i eksplosjonsvern: IIA, IIB og IIC etter IEC 60079-20-1. Inndeling, spaltevidder, tennstrømmer og typiske gasser."),
    "installation-inspection": ("Ex-installasjon og inspeksjon – Veiledning", "Krav til installasjon og inspeksjon av Ex-anlegg: IEC 60079-14/17, førstegangskontroll, periodisk kontroll og dokumentasjon."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Sammenligning", "Nordamerikansk NEC 500/505 og europeisk ATEX/IEC sammenlignet: Divisions vs. soner, vernemetoder og gjensidig anerkjennelse."),
    "protection-methods": ("Ex-vernemetoder – Komplett oversikt", "Alle Ex-vernemetoder forklart: flammesikker kapsling (d), egensikkerhet (i), støpemasse (m), overtrykk (p) og flere."),
    "standards": ("Eksplosjonsvern-standarder – IEC 60079", "Oversikt over de viktigste standardene i eksplosjonsvern: IEC 60079-serien, EN-standarder og bruksområder for Ex-utstyr."),
    "temperature-classes": ("Temperaturklasser T1–T6 i Ex-vern", "Temperaturklasser T1 til T6 forklart: maksimale overflatetemperaturer, tilhørende gasser og betydning for utstyrsvalg."),
    "zone-classification": ("Soneklassifisering – Sone 0, 1, 2, 20–22", "Soneklassifisering for gass og støv: sone 0/1/2 og sone 20/21/22 etter IEC 60079-10. Definisjoner, eksempler og framgangsmåte."),
    "atex-equipment-categories": ("ATEX-utstyrskategorier 1, 2 og 3", "ATEX-utstyrskategorier M1/M2, 1/2/3: vernenivåer, tillatte soner og krav til samsvarsvurdering etter 2014/34/EU."),
    "dsear-regulations-uk": ("DSEAR-forskriften (UK) – Oversikt", "Britisk DSEAR-forskrift for eksplosjonsvern: arbeidsgivers plikter, risikovurdering og forskjeller fra europeisk ATEX 153."),
},
"nl": {
    "index": ("ATEX & Ex-bescherming kennisbank – ExKnowledge", "Praktische kennis over ATEX, IECEx en explosiebeveiliging. Zone-indeling, beschermingsmethoden, apparaatcategorieën en normen helder uitgelegd."),
    "atex-directive": ("ATEX-richtlijn 2014/34/EU – Uitleg", "De ATEX-richtlijn helder uitgelegd: toepassingsgebied, conformiteitsbeoordeling, CE-markering en verplichtingen voor fabrikanten van Ex-apparatuur."),
    "atex-for-beginners": ("ATEX voor beginners – Eenvoudig uitgelegd", "ATEX-basiskennis begrijpelijk gemaakt: zones, apparaatcategorieën, Ex-markering en beschermingsconcepten. Het ideale startpunt voor nieuwkomers."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Verschillen vergeleken", "ATEX en IECEx naast elkaar gelegd: toepassingsgebied, wettelijke basis, markering en certificering. Wanneer geldt welke norm?"),
    "cable-glands-hazardous-areas": ("Ex-kabelwartels – Typen en selectie", "Kabelwartels voor Ex-zones: drukvaste (Ex d), verhoogde veiligheid (Ex e) en barrièretypen. Draadstandaarden, IP-klassen en veelgemaakte fouten."),
    "compex-certification": ("CompEx-certificering – Modules en carrière", "Alles over CompEx: modules Ex01–Ex14, opleidingsvereisten, geldigheid, verlenging en voordelen voor werken in explosiegevaarlijke gebieden."),
    "dust-explosion-protection": ("Stofexplosiebeveiliging – Zones en maatregelen", "Bescherming tegen stofexplosies: brandbaar stof, zone-indeling 20/21/22, ontstekingsbronnen en juiste maatregelen volgens IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Ex-apparatuur kiezen – Praktische gids", "Stap voor stap de juiste Ex-apparatuur kiezen: beslisschema's, zone-categorie koppeling en vergelijking van beschermingsmethoden."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Drukvast of intrinsiek veilig?", "Drukvaste behuizing (Ex d) en intrinsieke veiligheid (Ex i) technisch vergeleken: werkingsprincipes, toepassingen en keuzecriteria."),
    "hazardous-area-classification": ("Classificatie van gevaarlijke zones – Gids", "Zo worden Ex-zones ingedeeld: methodiek, emissiebronnen, ventilatiebeoordeling en documentatie-eisen volgens IEC 60079-10."),
    "how-to-read-atex-nameplate": ("ATEX-typeplaatje lezen – Decodering", "Leer ATEX-typeplaatjes correct lezen: CE-markering, categorieën, Ex-markering, temperatuurklassen en bijzondere voorwaarden met voorbeelden."),
    "hydrogen-explosion-protection": ("Explosiebeveiliging waterstof – IIC-apparatuur", "Waterstof vraagt om bijzondere explosiebeveiliging: breed ontvlambaarheidsgebied en lage ontstekingsenergie. Zo kiest u IIC-apparatuur."),
    "certification": ("Ex-certificering – ATEX en IECEx procedures", "Overzicht van Ex-certificeringsprocedures volgens ATEX en IECEx: keuringsinstanties, typeonderzoek en conformiteitsbeoordeling."),
    "cheat-sheet": ("ATEX-spiekbriefje – Snelle referentie", "ATEX en Ex-bescherming op één pagina: zones, categorieën, temperatuurklassen en beschermingsmethoden als handig naslagwerk."),
    "epl": ("Equipment Protection Level (EPL) – Uitleg", "Equipment Protection Levels volgens IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc en Ma/Mb. Koppeling met ATEX-categorieën en zones."),
    "ex-markings": ("Ex-markering begrijpen – Handleiding", "Ex-markeringen ontcijferd: beschermingsmethoden, gasgroepen, temperatuurklassen en EPL. Zo leest u de markering op Ex-apparatuur."),
    "faq": ("Veelgestelde vragen over ATEX en Ex", "Antwoorden op veelgestelde vragen over ATEX, IECEx, zone-indeling, beschermingsmethoden en Ex-markering."),
    "fundamentals": ("Basisprincipes explosiebeveiliging", "Basis van explosiebeveiliging: explosiedriehoek, ontstekingsbronnen, beschermingsprincipes en samenhang zones-categorieën-methoden."),
    "gas-groups": ("Gasgroepen IIA, IIB, IIC – Overzicht", "Gasgroepen in explosiebeveiliging: IIA, IIB en IIC volgens IEC 60079-20-1. Indeling, spleetwijdtes en kenmerkende gassen."),
    "installation-inspection": ("Ex-installatie en inspectie – Eisen", "Eisen aan installatie en inspectie van Ex-installaties: IEC 60079-14/17, initiële inspectie, periodieke controles en documentatie."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Vergelijking", "Noord-Amerikaans NEC 500/505 en Europees ATEX/IEC vergeleken: Divisions vs. zones, beschermingsmethoden en wederzijdse erkenning."),
    "protection-methods": ("Ex-beschermingsmethoden – Alle types", "Alle Ex-beschermingsmethoden: drukvaste behuizing (d), intrinsieke veiligheid (i), vergietmassa (m), overdruk (p) en meer."),
    "standards": ("Explosiebeveiliging normen – IEC 60079", "Overzicht van de belangrijkste normen voor explosiebeveiliging: IEC 60079-reeks, EN-normen en toepassingsgebieden."),
    "temperature-classes": ("Temperatuurklassen T1–T6 in Ex", "Temperatuurklassen T1 tot T6 uitgelegd: maximale oppervlaktetemperaturen, bijbehorende gassen en belang voor apparaatkeuze."),
    "zone-classification": ("Zone-indeling – Zone 0, 1, 2, 20–22", "Zone-indeling voor gas en stof: zone 0/1/2 en zone 20/21/22 volgens IEC 60079-10. Definities, voorbeelden en werkwijze."),
    "atex-equipment-categories": ("ATEX-apparaatcategorieën 1, 2 en 3", "ATEX-categorieën M1/M2, 1/2/3: beschermingsniveaus, toegestane zones en eisen aan conformiteitsbeoordeling per 2014/34/EU."),
    "dsear-regulations-uk": ("DSEAR-regelgeving (VK) – Overzicht", "De Britse DSEAR-regelgeving voor explosiebeveiliging: werkgeversplichten, risicobeoordeling en verschillen met de Europese ATEX 153."),
},
"sv": {
    "index": ("ATEX & Ex-skydd kunskapsbas – ExKnowledge", "Praktisk kunskap om ATEX, IECEx och explosionsskydd. Zonklassificering, skyddsmetoder, utrustningskategorier och standarder tydligt förklarade."),
    "atex-directive": ("ATEX-direktivet 2014/34/EU – Genomgång", "ATEX-utrustningsdirektivet förklarat: tillämpningsområde, bedömning av överensstämmelse, CE-märkning och skyldigheter för tillverkare."),
    "atex-for-beginners": ("ATEX för nybörjare – Enkel introduktion", "ATEX-grunder på svenska: zoner, utrustningskategorier, Ex-märkning och skyddskoncept. Det perfekta startskottet för explosionsskydd."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Skillnaderna förklarade", "ATEX och IECEx jämförda: geografiskt tillämpningsområde, rättslig grund, märkningsskillnader och certifieringsprocesser."),
    "cable-glands-hazardous-areas": ("Ex-kabelgenomföringar – Typer och val", "Kabelgenomföringar för Ex-områden: trycksäkra (Ex d), ökad säkerhet (Ex e) och barriärtyper. Gängstandarder, IP-klass och vanliga misstag."),
    "compex-certification": ("CompEx-certifiering – Moduler och karriär", "Allt om CompEx: moduler Ex01–Ex14, utbildningskrav, giltighet, förnyelse och karriärfördelar för arbete i explosionsfarliga områden."),
    "dust-explosion-protection": ("Dammexplosionsskydd – Zoner och åtgärder", "Skydd mot dammexplosioner: brännbart damm, zonklassificering 20/21/22, tändkällor och lämpliga åtgärder enligt IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Välja rätt Ex-utrustning – Praktisk guide", "Steg för steg till rätt Ex-utrustning: beslutsdiagram, koppling zon-kategori och jämförelse av skyddsmetoder för varje tillämpning."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Trycksäker eller egensäker?", "Trycksäker kapsling (Ex d) och egensäkerhet (Ex i) i teknisk jämförelse: funktionsprinciper, användningsområden och valkriterier."),
    "hazardous-area-classification": ("Klassificering av explosionsfarliga områden", "Så klassificeras Ex-områden i zoner: metodik, utsläppskällor, ventilationsbedömning och dokumentationskrav enligt IEC 60079-10."),
    "how-to-read-atex-nameplate": ("Läsa ATEX-typskylt – Komplett guide", "Lär dig avkoda ATEX-typskyltar: CE-märkning, kategorier, Ex-märkning, temperaturklasser och specialvillkor med verkliga exempel."),
    "hydrogen-explosion-protection": ("Explosionsskydd för vätgas – IIC-utrustning", "Vätgas kräver särskilt explosionsskydd: brett antändningsområde och låg antändningsenergi. Så väljer du rätt IIC-utrustning."),
    "certification": ("Ex-certifiering – ATEX och IECEx processer", "Översikt av Ex-certifiering enligt ATEX och IECEx: provningsorgan, typprovning, kvalitetssäkring och bedömning av överensstämmelse."),
    "cheat-sheet": ("ATEX-fusklapp – Snabbreferens", "ATEX och Ex-skydd på en sida: zoner, kategorier, temperaturklasser och skyddsmetoder som praktisk snabbreferens."),
    "epl": ("Equipment Protection Level (EPL) – Guide", "Equipment Protection Levels enligt IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc och Ma/Mb. Koppling till ATEX-kategorier och zoner."),
    "ex-markings": ("Ex-märkning – Så tolkar du den", "Förstå Ex-märkning: skyddsmetoder, gasgrupper, temperaturklasser och EPL. Så tolkar du märkningen på Ex-utrustning korrekt."),
    "faq": ("Vanliga frågor om ATEX och Ex-skydd", "Svar på vanliga frågor om ATEX, IECEx, zonklassificering, skyddsmetoder och Ex-märkning."),
    "fundamentals": ("Grundläggande om explosionsskydd", "Grunden för explosionsskydd: explosiontriangeln, tändkällor, skyddsprinciper och sambandet mellan zoner, kategorier och skyddsmetoder."),
    "gas-groups": ("Gasgrupper IIA, IIB, IIC – Översikt", "Gasgrupper inom explosionsskydd: IIA, IIB och IIC enligt IEC 60079-20-1. Indelning, spaltvidder och typiska gaser."),
    "installation-inspection": ("Ex-installation och inspektion – Krav", "Krav på installation och inspektion av Ex-anläggningar: IEC 60079-14/17, förstagångsinspektion, periodisk kontroll och dokumentation."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Jämförelse", "Nordamerikanskt NEC 500/505 och europeiskt ATEX/IEC jämfört: Divisions vs. zoner, skyddsmetoder och ömsesidigt erkännande."),
    "protection-methods": ("Ex-skyddsmetoder – Alla typer", "Alla Ex-skyddsmetoder: trycksäker kapsling (d), egensäkerhet (i), gjutmassa (m), övertryck (p) och fler."),
    "standards": ("Explosionsskyddsstandarder – IEC 60079", "Översikt av de viktigaste standarderna för explosionsskydd: IEC 60079-serien, EN-standarder och tillämpningsområden."),
    "temperature-classes": ("Temperaturklasser T1–T6 inom Ex-skydd", "Temperaturklasser T1 till T6 förklarade: maximala yttemperaturer, tillhörande gaser och betydelse för utrustningsval."),
    "zone-classification": ("Zonklassificering – Zon 0, 1, 2, 20–22", "Zonklassificering för gas och damm: zon 0/1/2 och zon 20/21/22 enligt IEC 60079-10. Definitioner, exempel och metodik."),
    "atex-equipment-categories": ("ATEX-utrustningskategorier 1, 2 och 3", "ATEX-kategorier M1/M2, 1/2/3: skyddsnivåer, tillåtna zoner och krav på bedömning av överensstämmelse enligt 2014/34/EU."),
    "dsear-regulations-uk": ("DSEAR-regler (UK) – Översikt", "Brittiska DSEAR-regler för explosionsskydd: arbetsgivarens skyldigheter, riskbedömning och skillnader mot europeisk ATEX 153."),
},
"da": {
    "index": ("ATEX & Ex-beskyttelse vidensbase – ExKnowledge", "Praktisk viden om ATEX, IECEx og eksplosionsbeskyttelse. Zoneklassificering, beskyttelsesmetoder, udstyrskategorier og standarder forklaret."),
    "atex-directive": ("ATEX-direktivet 2014/34/EU forklaret", "ATEX-udstyrsdirektivet forklaret: anvendelsesområde, overensstemmelsesvurdering, CE-mærkning og forpligtelser for producenter af Ex-udstyr."),
    "atex-for-beginners": ("ATEX for begyndere – Nem introduktion", "Grundlæggende ATEX på dansk: zoner, udstyrskategorier, Ex-mærkning og beskyttelseskoncepter. Det ideelle udgangspunkt for eksplosionsbeskyttelse."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Forskelle forklaret", "ATEX og IECEx sammenlignet: geografisk anvendelse, lovgrundlag, mærkningsforskelle og certificeringsprocesser. Hvornår gælder hvad?"),
    "cable-glands-hazardous-areas": ("Ex-kabelgennemføringer – Typer og valg", "Kabelgennemføringer til Ex-områder: flammesikre (Ex d), forhøjet sikkerhed (Ex e) og barrieretyper. Gevindstandarder, IP-klasse og fejl."),
    "compex-certification": ("CompEx-certificering – Moduler og karriere", "Alt om CompEx: moduler Ex01–Ex14, uddannelseskrav, gyldighed, fornyelse og karrierefordele for arbejde i eksplosionsfarlige områder."),
    "dust-explosion-protection": ("Støveksplosionsbeskyttelse – Zoner og tiltag", "Beskyttelse mod støveksplosioner: brændbart støv, zoneklassificering 20/21/22, tændkilder og udstyrvalg efter IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Vælg rigtigt Ex-udstyr – Praktisk guide", "Trin for trin til det rigtige Ex-udstyr: beslutningsdiagrammer, zone-kategori kobling og sammenligning af beskyttelsesmetoder."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – Flammesikker eller egensikker?", "Flammesikker kapsel (Ex d) og egensikkerhed (Ex i) teknisk sammenlignet: funktionsprincipper, anvendelser og udvælgelseskriterier."),
    "hazardous-area-classification": ("Klassificering af farlige områder – Guide", "Sådan klassificeres Ex-områder i zoner: metodik, udslipskilder, ventilationsvurdering og dokumentationskrav efter IEC 60079-10."),
    "how-to-read-atex-nameplate": ("Læs et ATEX-typeskilt – Komplet guide", "Lær at afkode ATEX-typeskilte: CE-mærkning, kategorier, Ex-mærkning, temperaturklasser og særlige betingelser med virkelige eksempler."),
    "hydrogen-explosion-protection": ("Eksplosionsbeskyttelse for brint – IIC-udstyr", "Brint kræver særlig eksplosionsbeskyttelse: bredt antændelsesområde og lav antændelsesenergi. Sådan vælger du IIC-godkendt udstyr."),
    "certification": ("Ex-certificering – ATEX og IECEx processer", "Oversigt over Ex-certificering efter ATEX og IECEx: prøvningsinstitutter, typeprøvning, kvalitetssikring og overensstemmelsesvurdering."),
    "cheat-sheet": ("ATEX-snydeark – Hurtig reference", "ATEX og Ex-beskyttelse på én side: zoner, kategorier, temperaturklasser og beskyttelsesmetoder som praktisk hurtig reference."),
    "epl": ("Equipment Protection Level (EPL) forklaret", "Equipment Protection Levels efter IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc og Ma/Mb. Kobling til ATEX-kategorier og zoner."),
    "ex-markings": ("Ex-mærkning – Sådan tolker du den", "Forstå Ex-mærkning: beskyttelsesmetoder, gasgrupper, temperaturklasser og EPL. Sådan læser du mærkningen på Ex-udstyr korrekt."),
    "faq": ("Ofte stillede spørgsmål om ATEX og Ex", "Svar på de mest stillede spørgsmål om ATEX, IECEx, zoneklassificering, beskyttelsesmetoder og Ex-mærkning."),
    "fundamentals": ("Grundlæggende om eksplosionsbeskyttelse", "Fundamentet for eksplosionsbeskyttelse: explosionstrekanten, tændkilder, beskyttelsesprincipper og sammenhængen zoner-kategorier."),
    "gas-groups": ("Gasgrupper IIA, IIB, IIC – Oversigt", "Gasgrupper i eksplosionsbeskyttelse: IIA, IIB og IIC efter IEC 60079-20-1. Inddeling, spaltevidder og typiske gasser."),
    "installation-inspection": ("Ex-installation og inspektion – Krav", "Krav til installation og inspektion af Ex-anlæg: IEC 60079-14/17, førstegangskontrol, periodisk kontrol og dokumentation."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Sammenligning", "Nordamerikansk NEC 500/505 og europæisk ATEX/IEC sammenlignet: Divisions vs. zoner, beskyttelsesmetoder og gensidig anerkendelse."),
    "protection-methods": ("Ex-beskyttelsesmetoder – Alle typer", "Alle Ex-beskyttelsesmetoder: flammesikker kapsel (d), egensikkerhed (i), støbemasse (m), overtryk (p) og flere."),
    "standards": ("Eksplosionsbeskyttelse standarder – IEC", "Oversigt over de vigtigste standarder i eksplosionsbeskyttelse: IEC 60079-serien, EN-standarder og anvendelsesområder."),
    "temperature-classes": ("Temperaturklasser T1–T6 i Ex-beskyttelse", "Temperaturklasser T1 til T6 forklaret: maksimale overfladetemperaturer, tilhørende gasser og betydning for udstyrvalg."),
    "zone-classification": ("Zoneklassificering – Zone 0, 1, 2, 20–22", "Zoneklassificering for gas og støv: zone 0/1/2 og zone 20/21/22 efter IEC 60079-10. Definitioner, eksempler og metodik."),
    "atex-equipment-categories": ("ATEX-udstyrskategorier 1, 2 og 3", "ATEX-kategorier M1/M2, 1/2/3: beskyttelsesniveauer, tilladte zoner og krav til overensstemmelsesvurdering efter 2014/34/EU."),
    "dsear-regulations-uk": ("DSEAR-regler (UK) – Oversigt", "Britisk DSEAR-regulering for eksplosionsbeskyttelse: arbejdsgiverens forpligtelser, risikovurdering og forskelle fra europæisk ATEX 153."),
},
"pt": {
    "index": ("Base de conhecimento ATEX e Ex – ExKnowledge", "Conhecimento prático sobre ATEX, IECEx e proteção contra explosões. Zonas, métodos de proteção, categorias de equipamentos e normas explicadas."),
    "atex-directive": ("Diretiva ATEX 2014/34/UE – Guia completo", "A diretiva ATEX de equipamentos explicada: âmbito, avaliação de conformidade, marcação CE e obrigações do fabricante de equipamentos Ex."),
    "atex-for-beginners": ("ATEX para iniciantes – Guia básico", "Conceitos básicos de ATEX em português: zonas, categorias de equipamentos, marcação Ex e princípios de proteção. Seu primeiro passo."),
    "atex-vs-iecex": ("ATEX vs. IECEx – Diferenças explicadas", "ATEX e IECEx comparados: âmbito geográfico, base legal, diferenças de marcação e processos de certificação. Qual norma se aplica?"),
    "cable-glands-hazardous-areas": ("Prensa-cabos Ex – Tipos e seleção", "Prensa-cabos para áreas Ex: à prova de explosão (Ex d), segurança aumentada (Ex e) e barreira. Roscas, IP e erros comuns."),
    "compex-certification": ("Certificação CompEx – Módulos e carreira", "Tudo sobre CompEx: módulos Ex01–Ex14, requisitos de formação, validade, renovação e benefícios profissionais para áreas perigosas."),
    "dust-explosion-protection": ("Proteção contra explosões de poeira", "Proteção contra explosões de poeira: tipos de poeira combustível, zonas 20/21/22, fontes de ignição e seleção de equipamentos por IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("Seleção de equipamentos Ex – Guia prático", "Como escolher equipamentos Ex passo a passo: fluxogramas de decisão, relação zona-categoria e comparação de métodos de proteção."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d vs. Ex i – À prova de explosão ou seguro?", "Invólucro à prova de explosão (Ex d) e segurança intrínseca (Ex i) em comparação técnica: princípios, aplicações e critérios."),
    "hazardous-area-classification": ("Classificação de áreas perigosas – Guia", "Como áreas perigosas são classificadas em zonas: metodologia, fontes de emissão, ventilação e documentação conforme IEC 60079-10."),
    "how-to-read-atex-nameplate": ("Ler placa ATEX – Guia de decodificação", "Aprenda a interpretar placas ATEX: marcação CE, categorias, marcação Ex, classes de temperatura e condições especiais com exemplos."),
    "hydrogen-explosion-protection": ("Proteção contra explosão de hidrogénio", "O hidrogénio exige proteção especial: ampla faixa de inflamabilidade e baixa energia de ignição. Guia para seleção de equipamentos IIC."),
    "certification": ("Certificação Ex – Processos ATEX e IECEx", "Visão geral da certificação Ex segundo ATEX e IECEx: organismos de certificação, ensaio de tipo e avaliação da conformidade."),
    "cheat-sheet": ("Folha de consulta ATEX – Referência rápida", "ATEX e proteção Ex numa página: zonas, categorias, classes de temperatura e métodos de proteção como referência prática."),
    "epl": ("Equipment Protection Level (EPL) – Guia", "Equipment Protection Levels conforme IEC 60079-0: Ga/Gb/Gc, Da/Db/Dc e Ma/Mb. Relação com categorias ATEX e zonas."),
    "ex-markings": ("Marcação Ex – Como interpretar", "Entenda a marcação Ex: métodos de proteção, grupos de gás, classes de temperatura e EPL. Como ler a marcação em equipamentos Ex."),
    "faq": ("Perguntas frequentes sobre ATEX e Ex", "Respostas às perguntas mais comuns sobre ATEX, IECEx, classificação de zonas, métodos de proteção e marcação Ex."),
    "fundamentals": ("Fundamentos da proteção contra explosões", "Base da proteção contra explosões: triângulo da explosão, fontes de ignição, princípios de proteção e relação zonas-categorias."),
    "gas-groups": ("Grupos de gás IIA, IIB, IIC – Visão geral", "Grupos de gás na proteção contra explosões: IIA, IIB e IIC conforme IEC 60079-20-1. Classificação, interstícios e gases típicos."),
    "installation-inspection": ("Instalação e inspeção Ex – Requisitos", "Requisitos para instalação e inspeção de equipamentos Ex: IEC 60079-14/17, verificação inicial, inspeções periódicas e documentação."),
    "nec-500-vs-atex-iec": ("NEC 500 vs. ATEX/IEC – Comparação", "Sistema norte-americano NEC 500/505 e europeu ATEX/IEC comparados: Divisions vs. zonas e reconhecimento mútuo."),
    "protection-methods": ("Métodos de proteção Ex – Todos os tipos", "Todos os métodos de proteção Ex: invólucro à prova de explosão (d), segurança intrínseca (i), encapsulamento (m), pressurização (p) e mais."),
    "standards": ("Normas de proteção contra explosões – IEC", "Visão geral das principais normas de proteção contra explosões: série IEC 60079, normas EN e seus âmbitos de aplicação."),
    "temperature-classes": ("Classes de temperatura T1–T6 em Ex", "Classes de temperatura T1 a T6 explicadas: temperaturas máximas de superfície, gases associados e importância na seleção de equipamentos."),
    "zone-classification": ("Classificação de zonas – 0, 1, 2, 20–22", "Classificação de zonas para gás e poeira: zona 0/1/2 e zona 20/21/22 conforme IEC 60079-10. Definições e metodologia."),
    "atex-equipment-categories": ("Categorias de equipamentos ATEX – 1, 2, 3", "Categorias ATEX M1/M2, 1/2/3: níveis de proteção, zonas permitidas e requisitos de avaliação da conformidade per 2014/34/UE."),
    "dsear-regulations-uk": ("Regulamento DSEAR (Reino Unido) – Resumo", "Regulamento DSEAR britânico para proteção contra explosões: obrigações do empregador, avaliação de riscos e diferenças da ATEX 153."),
},
"ar": {
    "index": ("قاعدة معرفة ATEX والحماية من الانفجار – ExKnowledge", "معرفة عملية حول ATEX وIECEx والحماية من الانفجار. تصنيف المناطق وطرق الحماية وفئات المعدات والمعايير موضحة بشكل مبسط."),
    "atex-directive": ("توجيه ATEX 2014/34/EU – دليل شامل", "شرح توجيه معدات ATEX: النطاق وتقييم المطابقة وعلامة CE والتزامات المصنّع للمعدات المستخدمة في الأجواء المتفجرة."),
    "atex-for-beginners": ("ATEX للمبتدئين – مقدمة مبسطة", "أساسيات ATEX بلغة واضحة: المناطق وفئات المعدات وعلامات Ex ومبادئ الحماية. نقطة البداية المثالية في عالم الحماية من الانفجار."),
    "atex-vs-iecex": ("ATEX مقابل IECEx – أبرز الفروقات", "مقارنة ATEX وIECEx: النطاق الجغرافي والأساس القانوني واختلافات العلامات وعمليات التصديق. متى يُطبَّق كل معيار؟"),
    "cable-glands-hazardous-areas": ("وصلات الكابلات Ex – الأنواع والاختيار", "وصلات كابلات للمناطق الخطرة: مقاومة اللهب (Ex d) وأمان مُعزَّز (Ex e) وحاجز. معايير اللولب وتصنيف IP والأخطاء الشائعة."),
    "compex-certification": ("شهادة CompEx – الوحدات والمسار المهني", "كل ما تحتاجه عن CompEx: الوحدات Ex01–Ex14 ومتطلبات التدريب والصلاحية والتجديد والمزايا المهنية للعمل في المناطق الخطرة."),
    "dust-explosion-protection": ("الحماية من انفجارات الغبار – المناطق والتدابير", "الوقاية من انفجارات الغبار: أنواع الغبار القابل للاشتعال وتصنيف المناطق 20/21/22 ومصادر الاشتعال واختيار المعدات وفق IEC 60079-10-2."),
    "ex-equipment-selection-guide": ("دليل اختيار معدات Ex – دليل عملي", "اختيار معدات Ex خطوة بخطوة: مخططات القرار وربط المنطقة بالفئة ومقارنة طرق الحماية والتوصيات حسب التطبيق."),
    "explosion-proof-vs-intrinsically-safe": ("Ex d مقابل Ex i – مقاوم للانفجار أم آمن جوهرياً؟", "الغلاف المقاوم للانفجار (Ex d) والأمان الجوهري (Ex i) في مقارنة تقنية: المبادئ والتطبيقات ومعايير الاختيار."),
    "hazardous-area-classification": ("تصنيف المناطق الخطرة – دليل شامل", "كيف تُصنَّف المناطق الخطرة إلى مناطق: المنهجية ومصادر الانبعاث وتقييم التهوية ومتطلبات التوثيق وفق IEC 60079-10."),
    "how-to-read-atex-nameplate": ("قراءة لوحة ATEX – دليل فك الرموز", "تعلَّم قراءة لوحات ATEX خطوة بخطوة: علامة CE والفئات وعلامات Ex ودرجات الحرارة والشروط الخاصة مع أمثلة واقعية."),
    "hydrogen-explosion-protection": ("حماية انفجار الهيدروجين – معدات IIC", "الهيدروجين يتطلب حماية خاصة: نطاق اشتعال واسع وطاقة إشعال منخفضة. دليل اختيار المعدات المعتمدة IIC."),
    "certification": ("شهادة Ex – عمليات ATEX وIECEx", "نظرة عامة على شهادات Ex وفق ATEX وIECEx: هيئات التصديق واختبار النوع وضمان الجودة وتقييم المطابقة."),
    "cheat-sheet": ("ورقة مرجعية ATEX – مرجع سريع", "ATEX والحماية Ex في صفحة واحدة: المناطق والفئات ودرجات الحرارة وطرق الحماية كمرجع سريع عملي."),
    "epl": ("مستوى حماية المعدات (EPL) – دليل", "مستويات حماية المعدات وفق IEC 60079-0: Ga/Gb/Gc وDa/Db/Dc وMa/Mb. العلاقة مع فئات ATEX والمناطق."),
    "ex-markings": ("علامات Ex – كيف تفسرها", "فهم علامات Ex: طرق الحماية ومجموعات الغاز ودرجات الحرارة وEPL. دليل قراءة العلامات على معدات Ex."),
    "faq": ("أسئلة شائعة حول ATEX والحماية Ex", "إجابات على الأسئلة الأكثر شيوعاً حول ATEX وIECEx وتصنيف المناطق وطرق الحماية وعلامات Ex."),
    "fundamentals": ("أساسيات الحماية من الانفجار", "أسس الحماية من الانفجار: مثلث الانفجار ومصادر الاشتعال ومبادئ الحماية والعلاقة بين المناطق والفئات والطرق."),
    "gas-groups": ("مجموعات الغاز IIA وIIB وIIC – نظرة عامة", "مجموعات الغاز في الحماية من الانفجار: IIA وIIB وIIC وفق IEC 60079-20-1. التصنيف والفجوات والغازات النموذجية."),
    "installation-inspection": ("تركيب وفحص Ex – المتطلبات", "متطلبات تركيب وفحص منشآت Ex: IEC 60079-14/17 والفحص الأولي والفحوصات الدورية والتوثيق."),
    "nec-500-vs-atex-iec": ("NEC 500 مقابل ATEX/IEC – مقارنة", "النظام الأمريكي NEC 500/505 والأوروبي ATEX/IEC مقارنة: التقسيمات مقابل المناطق وطرق الحماية والاعتراف المتبادل."),
    "protection-methods": ("طرق حماية Ex – جميع الأنواع", "جميع طرق حماية Ex: الغلاف المقاوم للانفجار (d) والأمان الجوهري (i) والتغليف (m) والضغط الزائد (p) وغيرها."),
    "standards": ("معايير الحماية من الانفجار – IEC 60079", "نظرة عامة على أهم معايير الحماية من الانفجار: سلسلة IEC 60079 ومعايير EN ونطاقات تطبيقها."),
    "temperature-classes": ("فئات الحرارة T1–T6 في حماية Ex", "فئات الحرارة T1 إلى T6 موضحة: الحرارة السطحية القصوى والغازات المرتبطة وأهميتها في اختيار المعدات."),
    "zone-classification": ("تصنيف المناطق – 0 و1 و2 و20–22", "تصنيف مناطق الغاز والغبار: منطقة 0/1/2 ومنطقة 20/21/22 وفق IEC 60079-10. التعريفات والأمثلة والمنهجية."),
    "atex-equipment-categories": ("فئات معدات ATEX – 1 و2 و3", "فئات ATEX M1/M2 و1/2/3: مستويات الحماية والمناطق المسموحة ومتطلبات تقييم المطابقة وفق 2014/34/EU."),
    "dsear-regulations-uk": ("لوائح DSEAR البريطانية – نظرة عامة", "لوائح DSEAR البريطانية للحماية من الانفجار: التزامات صاحب العمل وتقييم المخاطر والاختلافات عن ATEX 153 الأوروبية."),
},
}

count = 0
for lang, pages in DATA.items():
    for page, (title, desc) in pages.items():
        if page == "index":
            fp = BASE / lang / "index.html"
        else:
            fp = BASE / lang / "pages" / f"{page}.html"
        if fp.exists():
            update_file(fp, title, desc)
            count += 1
        else:
            print(f"MISSING: {fp}")

print(f"Updated {count} files with new titles and descriptions")
